import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./services/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1a1c1f",
        background: "#141313",
        "surface-container": "#201f20",
        "on-surface": "#e5e2e1",
        primary: "#ffffff",
        "tertiary-container": "#ede0d7",
        "on-primary-container": "#636469",
        "on-secondary-container": "#b5b5b9",
        "on-primary": "#2e3034",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#45474a",
        "on-tertiary": "#362f29",
        "surface-tint": "#c6c6cb",
        "primary-container": "#e2e2e7",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#201a15",
        "inverse-primary": "#5d5e63",
        error: "#ffb4ab",
        "surface-dim": "#141313",
        "secondary-fixed": "#e3e2e6",
        "secondary-fixed-dim": "#c6c6ca",
        "primary-fixed-dim": "#c6c6cb",
        "on-secondary": "#2f3034",
        "surface-variant": "#353435",
        "on-primary-fixed": "#1a1c1f",
        outline: "#909095",
        "secondary-container": "#45474a",
        "surface-container-highest": "#353435",
        tertiary: "#ffffff",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e1",
        surface: "#141313",
        "tertiary-fixed": "#ede0d7",
        "surface-container-low": "#1c1b1c",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#45474a",
        secondary: "#c6c6ca",
        "surface-bright": "#3a3939",
        "primary-fixed": "#e2e2e7",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#45474b",
        "on-surface-variant": "#c6c6ca",
        "tertiary-fixed-dim": "#d0c4bc",
        "on-tertiary-container": "#6c635c",
        "on-tertiary-fixed-variant": "#4d453f",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
      },
      fontFamily: {
        inter: ["var(--font-inter)", "sans-serif"],
        headline: ["var(--font-hanken)", "sans-serif"],
        "mono-data": ["var(--font-geist)", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        "margin-mobile": "20px",
        "unit-xs": "4px",
        "unit-sm": "8px",
        "unit-md": "16px",
        "unit-lg": "24px",
        "unit-xl": "48px",
        "container-max": "1440px",
      },
      boxShadow: {
        "card-shadow": "0 4px 20px rgba(0, 0, 0, 0.4)",
        "modal-shadow": "0 20px 60px rgba(0, 0, 0, 0.8)",
      },
    },
  },
  plugins: [],
};

export default config;
