import { Ground } from "@/types/ground";

export const MOCK_GROUNDS: Ground[] = [
  {
    id: "mcg",
    name: "Melbourne Cricket Ground",
    shortName: "MCG",
    city: "Melbourne",
    country: "Australia",
    capacity: 100024,
    pitchType: "Pace-Friendly",
    imageUrl: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80",
    stats: {
      T20I: {
        totalMatches: 24,
        avgFirstInningsScore: 161,
        avgSecondInningsScore: 144,
        highestTotal: "186/5 (IND vs ZIM)",
        lowestTotal: "74/10 (IND vs AUS)",
        battingFirstWinPct: 41.7,
        chasingWinPct: 58.3,
        paceWicketsPct: 76.4,
        spinWicketsPct: 23.6,
        dayWinPct: 50.0,
        nightWinPct: 50.0,
      },
      ODI: {
        totalMatches: 158,
        avgFirstInningsScore: 222,
        avgSecondInningsScore: 198,
        highestTotal: "344/8 (AUS vs ENG)",
        lowestTotal: "94/10 (ENG vs AUS)",
        battingFirstWinPct: 48.1,
        chasingWinPct: 51.9,
        paceWicketsPct: 72.8,
        spinWicketsPct: 27.2,
        dayWinPct: 45.2,
        nightWinPct: 54.8,
      },
      TEST: {
        totalMatches: 116,
        avgFirstInningsScore: 308,
        avgSecondInningsScore: 284,
        highestTotal: "624/8d (AUS vs PAK)",
        lowestTotal: "36/10 (AUS vs SA)",
        battingFirstWinPct: 52.6,
        chasingWinPct: 47.4,
        paceWicketsPct: 81.2,
        spinWicketsPct: 18.8,
        dayWinPct: 100.0,
        nightWinPct: 0.0,
      },
    },
    boundaryDimensions: {
      straight: 85,
      squareLeg: 78,
      cover: 80,
      fineLeg: 74,
      thirdMan: 72,
      longOn: 86,
      longOff: 84,
    },
    historicalRecords: {
      highestIndividualScore: "250 (Ricky Ponting vs PAK)",
      bestBowlingFigures: "7/46 (Dennis Lillee vs ENG)",
      highestSuccessfulChase: "332/7 (AUS vs ENG)",
    },
    weatherForecastPlaceholder: {
      tempC: 22,
      humidityPct: 58,
      condition: "Partly Cloudy / Seam Movement Likely",
      rainProbabilityPct: 15,
    },
  },
  {
    id: "lords",
    name: "Lord's Cricket Ground",
    shortName: "Lord's",
    city: "London",
    country: "England",
    capacity: 31100,
    pitchType: "Balanced / Sporting",
    imageUrl: "https://images.unsplash.com/photo-1517649763962-0c623266010b?w=800&auto=format&fit=crop&q=80",
    stats: {
      TEST: {
        totalMatches: 144,
        avgFirstInningsScore: 312,
        avgSecondInningsScore: 295,
        highestTotal: "729/6d (AUS vs ENG)",
        lowestTotal: "42/10 (IND vs ENG)",
        battingFirstWinPct: 50.7,
        chasingWinPct: 49.3,
        paceWicketsPct: 78.5,
        spinWicketsPct: 21.5,
        dayWinPct: 100.0,
        nightWinPct: 0.0,
      },
      ODI: {
        totalMatches: 68,
        avgFirstInningsScore: 238,
        avgSecondInningsScore: 214,
        highestTotal: "334/4 (ENG vs IND)",
        lowestTotal: "107/10 (RSA vs ENG)",
        battingFirstWinPct: 54.4,
        chasingWinPct: 45.6,
        paceWicketsPct: 74.2,
        spinWicketsPct: 25.8,
        dayWinPct: 60.0,
        nightWinPct: 40.0,
      },
      T20I: {
        totalMatches: 12,
        avgFirstInningsScore: 152,
        avgSecondInningsScore: 138,
        highestTotal: "183/5 (ENG vs PAK)",
        lowestTotal: "93/10 (NED vs ENG)",
        battingFirstWinPct: 58.3,
        chasingWinPct: 41.7,
        paceWicketsPct: 71.0,
        spinWicketsPct: 29.0,
        dayWinPct: 50.0,
        nightWinPct: 50.0,
      },
    },
    boundaryDimensions: {
      straight: 74,
      squareLeg: 68,
      cover: 71,
      fineLeg: 65,
      thirdMan: 64,
      longOn: 75,
      longOff: 73,
    },
    historicalRecords: {
      highestIndividualScore: "333 (Graham Gooch vs IND)",
      bestBowlingFigures: "8/34 (Ian Botham vs PAK)",
      highestSuccessfulChase: "344/1 (WINDIES vs ENG)",
    },
    weatherForecastPlaceholder: {
      tempC: 18,
      humidityPct: 72,
      condition: "Overcast / High Swing Conditions",
      rainProbabilityPct: 35,
    },
  },
];
