import { Player } from "@/types/player";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "virat-kohli",
    name: "Virat Kohli",
    fullName: "Virat Kohli",
    country: "India",
    countryCode: "IND",
    role: "BATTER",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    iccRankings: {
      test: 5,
      odi: 1,
      t20i: 12,
    },
    avatarUrl: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=400&auto=format&fit=crop&q=80",
    countryFlagUrl: "https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=100&auto=format&fit=crop&q=80",
    primaryColor: "#0055a5", // India Blue
    accentColor: "#ff9933", // Saffron Accent
    stats: {
      TEST: {
        batting: {
          matches: 113,
          innings: 191,
          runs: 8848,
          highestScore: "254*",
          average: 49.15,
          strikeRate: 55.56,
          hundreds: 29,
          fifties: 30,
          fours: 991,
          sixes: 26,
          boundaryPercentage: 54.2,
          dotBallPercentage: 62.4,
        },
      },
      ODI: {
        batting: {
          matches: 292,
          innings: 280,
          runs: 13848,
          highestScore: "183",
          average: 58.67,
          strikeRate: 93.58,
          hundreds: 50,
          fifties: 72,
          fours: 1294,
          sixes: 151,
          boundaryPercentage: 58.9,
          dotBallPercentage: 42.1,
        },
      },
      T20I: {
        batting: {
          matches: 125,
          innings: 117,
          runs: 4188,
          highestScore: "122*",
          average: 48.69,
          strikeRate: 137.04,
          hundreds: 1,
          fifties: 38,
          fours: 361,
          sixes: 124,
          boundaryPercentage: 61.5,
          dotBallPercentage: 35.8,
        },
      },
      ALL: {
        batting: {
          matches: 530,
          innings: 588,
          runs: 26884,
          highestScore: "254*",
          average: 53.22,
          strikeRate: 79.4,
          hundreds: 80,
          fifties: 140,
          fours: 2646,
          sixes: 301,
          boundaryPercentage: 57.1,
          dotBallPercentage: 46.8,
        },
      },
    },
    phaseAnalysis: {
      ODI: {
        powerplay: { runs: 2450, strikeRate: 84.5, dismissals: 28, dotBallPct: 52.1 },
        middleOvers: { runs: 8920, strikeRate: 92.8, dismissals: 142, dotBallPct: 38.4 },
        deathOvers: { runs: 2478, strikeRate: 168.4, dismissals: 62, dotBallPct: 22.3 },
      },
      T20I: {
        powerplay: { runs: 1210, strikeRate: 118.2, dismissals: 18, dotBallPct: 44.2 },
        middleOvers: { runs: 2150, strikeRate: 134.6, dismissals: 48, dotBallPct: 32.1 },
        deathOvers: { runs: 828, strikeRate: 194.2, dismissals: 24, dotBallPct: 18.5 },
      },
      TEST: {
        powerplay: { runs: 1200, strikeRate: 48.2, dismissals: 30, dotBallPct: 72.1 },
        middleOvers: { runs: 6200, strikeRate: 56.4, dismissals: 120, dotBallPct: 61.2 },
        deathOvers: { runs: 1448, strikeRate: 68.9, dismissals: 41, dotBallPct: 55.4 },
      },
      ALL: {
        powerplay: { runs: 4860, strikeRate: 83.6, dismissals: 76, dotBallPct: 56.13 },
        middleOvers: { runs: 17270, strikeRate: 94.6, dismissals: 310, dotBallPct: 43.9 },
        deathOvers: { runs: 4754, strikeRate: 143.8, dismissals: 127, dotBallPct: 32.06 },
      },
    },
    matchups: [
      {
        bowlerName: "Adam Zampa",
        bowlerType: "Right-arm legbreak",
        runsScored: 248,
        ballsFaced: 236,
        dismissals: 5,
        strikeRate: 105.08,
        dotBallPercentage: 38.2,
      },
      {
        bowlerName: "Mitchell Starc",
        bowlerType: "Left-arm fast",
        runsScored: 196,
        ballsFaced: 214,
        dismissals: 4,
        strikeRate: 91.58,
        dotBallPercentage: 46.7,
      },
      {
        bowlerName: "James Anderson",
        bowlerType: "Right-arm fast-medium",
        runsScored: 305,
        ballsFaced: 710,
        dismissals: 7,
        strikeRate: 42.95,
        dotBallPercentage: 74.3,
      },
      {
        bowlerName: "Rashid Khan",
        bowlerType: "Right-arm legbreak",
        runsScored: 112,
        ballsFaced: 104,
        dismissals: 2,
        strikeRate: 107.69,
        dotBallPercentage: 36.5,
      },
    ],
    formTrend: [
      { match: "vs AUS (ODI)", runs: 85, opponent: "Australia", date: "2024-11-12" },
      { match: "vs NZ (ODI)", runs: 117, opponent: "New Zealand", date: "2024-11-04" },
      { match: "vs SA (T20I)", runs: 76, opponent: "South Africa", date: "2024-06-29" },
      { match: "vs ENG (Test)", runs: 54, opponent: "England", date: "2024-03-15" },
      { match: "vs PAK (ODI)", runs: 122, opponent: "Pakistan", date: "2023-09-11" },
    ],
    radarMetrics: {
      consistency: 96,
      powerHitting: 84,
      spinAdaptability: 91,
      paceAdaptability: 98,
      pressureHandling: 99,
      clutchIndex: 97,
    },
  },
  {
    id: "travis-head",
    name: "Travis Head",
    fullName: "Travis Michael Head",
    country: "Australia",
    countryCode: "AUS",
    role: "BATTER",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    iccRankings: {
      test: 10,
      odi: 5,
      t20i: 1,
    },
    avatarUrl: "https://images.unsplash.com/photo-1508802913482-f309e1e57322?w=400&auto=format&fit=crop&q=80",
    countryFlagUrl: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=100&auto=format&fit=crop&q=80",
    primaryColor: "#ffcd00", // Australia Gold
    accentColor: "#00843d", // Green Accent
    stats: {
      TEST: {
        batting: {
          matches: 49,
          innings: 84,
          runs: 3173,
          highestScore: "175",
          average: 41.75,
          strikeRate: 63.45,
          hundreds: 7,
          fifties: 16,
          fours: 410,
          sixes: 28,
          boundaryPercentage: 58.1,
          dotBallPercentage: 58.9,
        },
      },
      ODI: {
        batting: {
          matches: 65,
          innings: 62,
          runs: 2397,
          highestScore: "154*",
          average: 42.8,
          strikeRate: 106.15,
          hundreds: 5,
          fifties: 15,
          fours: 290,
          sixes: 54,
          boundaryPercentage: 64.2,
          dotBallPercentage: 40.1,
        },
      },
      T20I: {
        batting: {
          matches: 38,
          innings: 38,
          runs: 1084,
          highestScore: "91",
          average: 32.84,
          strikeRate: 158.47,
          hundreds: 0,
          fifties: 5,
          fours: 124,
          sixes: 52,
          boundaryPercentage: 68.9,
          dotBallPercentage: 31.4,
        },
      },
      ALL: {
        batting: {
          matches: 152,
          innings: 184,
          runs: 6654,
          highestScore: "175",
          average: 40.82,
          strikeRate: 94.2,
          hundreds: 12,
          fifties: 36,
          fours: 824,
          sixes: 134,
          boundaryPercentage: 63.7,
          dotBallPercentage: 43.46,
        },
      },
    },
    radarMetrics: {
      consistency: 82,
      powerHitting: 95,
      spinAdaptability: 88,
      paceAdaptability: 92,
      pressureHandling: 94,
      clutchIndex: 96,
    },
    formTrend: [
      { match: "vs IND (Test)", runs: 137, opponent: "India", date: "2024-11-22" },
      { match: "vs ENG (T20I)", runs: 59, opponent: "England", date: "2024-09-11" },
      { match: "vs SCO (T20I)", runs: 80, opponent: "Scotland", date: "2024-09-04" },
    ],
  },
  {
    id: "jofra-archer",
    name: "Jofra Archer",
    fullName: "Jofra Daniel Archer",
    country: "England",
    countryCode: "ENG",
    role: "BOWLER",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    iccRankings: {
      test: 18,
      odi: 14,
      t20i: 8,
    },
    avatarUrl: "https://images.unsplash.com/photo-1517649763962-0c623266010b?w=400&auto=format&fit=crop&q=80",
    countryFlagUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=100&auto=format&fit=crop&q=80",
    primaryColor: "#1d70b8", // England Blue
    accentColor: "#d4351c", // Red Accent
    stats: {
      TEST: {
        batting: {
          matches: 13,
          innings: 20,
          runs: 310,
          highestScore: "30",
          average: 17.22,
          strikeRate: 48.2,
          hundreds: 0,
          fifties: 0,
          fours: 35,
          sixes: 8,
          boundaryPercentage: 60.0,
          dotBallPercentage: 70.0,
        },
        bowling: {
          matches: 13,
          overs: 432.5,
          wickets: 42,
          bestBowling: "6/45",
          average: 31.04,
          economy: 3.01,
          strikeRate: 61.8,
          fiveWickets: 3,
          dotBallPercentage: 71.4,
        },
      },
      ODI: {
        batting: {
          matches: 21,
          innings: 10,
          runs: 95,
          highestScore: "24",
          average: 11.87,
          strikeRate: 88.0,
          hundreds: 0,
          fifties: 0,
          fours: 8,
          sixes: 3,
          boundaryPercentage: 54.0,
          dotBallPercentage: 45.0,
        },
        bowling: {
          matches: 21,
          overs: 190.4,
          wickets: 42,
          bestBowling: "6/40",
          average: 24.85,
          economy: 5.48,
          strikeRate: 27.2,
          fiveWickets: 2,
          dotBallPercentage: 58.2,
        },
      },
      T20I: {
        batting: {
          matches: 25,
          innings: 12,
          runs: 72,
          highestScore: "18*",
          average: 12.0,
          strikeRate: 125.0,
          hundreds: 0,
          fifties: 0,
          fours: 6,
          sixes: 3,
          boundaryPercentage: 58.0,
          dotBallPercentage: 35.0,
        },
        bowling: {
          matches: 25,
          overs: 95.0,
          wickets: 32,
          bestBowling: "3/12",
          average: 22.4,
          economy: 7.55,
          strikeRate: 17.8,
          fiveWickets: 0,
          dotBallPercentage: 48.9,
        },
      },
      ALL: {
        batting: {
          matches: 59,
          innings: 42,
          runs: 477,
          highestScore: "30",
          average: 14.45,
          strikeRate: 67.4,
          hundreds: 0,
          fifties: 0,
          fours: 49,
          sixes: 14,
          boundaryPercentage: 57.3,
          dotBallPercentage: 50.0,
        },
        bowling: {
          matches: 59,
          overs: 717.9,
          wickets: 116,
          bestBowling: "6/40",
          average: 26.41,
          economy: 4.26,
          strikeRate: 37.13,
          fiveWickets: 5,
          dotBallPercentage: 62.83,
        },
      },
    },
    radarMetrics: {
      consistency: 85,
      powerHitting: 70,
      spinAdaptability: 60,
      paceAdaptability: 99,
      pressureHandling: 92,
      clutchIndex: 94,
    },
    formTrend: [
      { match: "vs SA (ODI)", runs: 0, opponent: "South Africa", date: "2024-09-20" },
      { match: "vs AUS (T20I)", runs: 0, opponent: "Australia", date: "2024-09-13" },
    ],
  },
];
